version: "3.3"

networks:
  demo-network:

services:
  demo-app:
    build: ../../
    restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_PORT:
      DEVTOOL_SECRET:
    networks:
      demo-network:
    ports:
      - "${API_PORT}:8080"
      - "${API_DEBUG_PORT}:5005"
    depends_on:
      - demo-db

  demo-db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    networks:
      demo-network:
    ports:
      - "${POSTGRES_PORT}:5432"